// This file is auto-generated by Momentum Trail
// Any changes will be discarded on the next run
// php artisan routes:generate

import getRoute from "ziggy-js"
import { url, routes, wildcards, defaults } from "./routes.json"

export type Routes = keyof typeof routes
export type Wildcards = keyof typeof wildcards

export function route<Routes extends typeof routes, Route extends keyof Routes>(
  name: Route,
  params?:
    | (Routes[Route] extends { bindings: any }
        ? Partial<Record<keyof Routes[Route]["bindings"], any>> & Record<string, any>
        : {})
    | string
    | number
) {
  return getRoute(name as any, params as any, true, { url, routes, defaults } as any).toString()
}

export function current<
  Routes extends typeof routes,
  Wildcards extends typeof wildcards,
  Route extends keyof Routes | keyof Wildcards
>(
  name?: Route,
  params?: Route extends keyof Routes
    ?
        | (Routes[Route] extends { bindings: any }
            ? Partial<Record<keyof Routes[Route]["bindings"], any>> & Record<string, any>
            : {})
        | string
        | number
    : {}
): boolean | string {
  return getRoute(undefined, undefined, false, { url, routes, defaults } as any).current(name as string, params as any)
}
